name: documentation

on:
  push:
    branches: [development]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser
        pip install -r requirements/requirements.txt
        
    - name: Debug Info
      run: |
        pwd
        ls -la
        echo "Contents of docs directory:"
        ls -la docs/
        echo "Contents of docs/source directory:"
        ls -la docs/source/
        
    - name: Build documentation
      run: |
        cd docs
        make html
        echo "Contents of build/html directory:"
        ls -la build/html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy documentation'